### ISSUE TITLE
Orçamento e custo parciais

### ISSUE THREAD

**Issue by RenatoLAG** [RenatoLAG/Braco-robotico#11]
Pesquisar os materiais necessários para a montagem do protótipo e seus respectivos valores

**Comment by Suzielen** [comment]
Irei inserir o orçamento parcial, pois ainda precisamos definir alguns pontos do projeto. 
[Orçamento Parcial.xlsx](https://github.com/RenatoLAG/Braco-robotico/files/1628825/Orcamento.Parcial.xlsx)

**Comment by RenatoLAG** [comment]
muito bem

**Comment by hyperiondeimos** [comment]
Valores errados e incompletos. Um atuador pneumatico de dupla ação por menos de R$ 50,00? Duvido que exista, ainda mais o FESTO que eu emprestei. Por favor, façam o trabalho direito pois isso impactará na atividade de fechamento da Sprint #3. Ajustem isso

**Comment by vrlimaa** [comment]
Amanhã irei postar uma planilha atualizada com os valores dos materiais, ferramentas, custo e mão-de-obra da confecção da esteira.

**Comment by vrlimaa** [comment]
Com a alteração do projeto final, acarretou em algumas mudanças significativas no para o custo total final, sendo assim, irão ser feitos novos levantamentos, levando em conta tudo aquilo que não será alterado no novo projeto. Porém, logo, iremos utilizar um tempo maior para finalizar o restante do orçamento.

**Comment by Suzielen** [comment]
A planilha com os valores atualizados serão postados no Épico _Orçamento e custos finais_ .
