### ISSUE TITLE
Revisão sistemática

### ISSUE THREAD

**Issue by RenatoLAG** [RenatoLAG/Braco-robotico#13]
Após os artigos serem encontrados, realizar a revisão sistemática afim de verificar melhorias que possam ser feitas no nosso projeto e identificar quais métodos de pesquisa foram utilizados para auxiliar na escrita do relatório final.

**Comment by TaynaM** [comment]
Aqui está a revisão sistemáticas dos artigos encontrados pela Suzielen e por mim.
[Eventos.docx](https://github.com/RenatoLAG/Braco-robotico/files/1628948/Eventos.docx)

**Comment by TaynaM** [comment]
Abaixo encontra-se a revisão sistemática dos artigos encontrados pela Suzielen e por mim.

[Fichamentos.finalizados.docx](https://github.com/RenatoLAG/Braco-robotico/files/1632942/Fichamentos.finalizados.docx)

**Comment by hyperiondeimos** [comment]
Tem algumas falhas, mas tudo bem. Darei como fechado.

**Comment by hyperiondeimos** [comment]
Só enviem da próxima vez em PDF.
