### ISSUE TITLE
Locais para a publicação do artigo

### ISSUE THREAD

**Issue by RenatoLAG** [RenatoLAG/Braco-robotico#14]
Pesquisar locais (eventos, seminários, congressos, revistas) para a publicação do artigo

**Comment by TaynaM** [comment]
Os locais encontrados para a publicação do artigo encontram-se no documento abaixo 
[Eventos.docx](https://github.com/RenatoLAG/Braco-robotico/files/1628954/Eventos.docx)

**Comment by hyperiondeimos** [comment]
alguns dos eventos NÃO são indicados para o projeto de vocês, pois aborda muito pouco sobre visão e também sobre robotica. Mas darei como concluido.
