### ISSUE TITLE
Material para montagem do braço robótico

### ISSUE THREAD

**Issue by RenatoLAG** [RenatoLAG/Braco-robotico#15]
Disponibilizar aqui o manual para a montagem do braço robótico e em seguida realizar a montagem

**Comment by TaynaM** [comment]
Aqui está o manual
[bracoslim.pdf](https://github.com/RenatoLAG/Braco-robotico/files/1628975/bracoslim.pdf)

**Comment by Suzielen** [comment]
Necessito dos 4 servos motores para montagem completa da estrutura do braço robótico.

**Comment by hyperiondeimos** [comment]
Falta algo ainda?

**Comment by hyperiondeimos** [comment]
Falta algo ainda?

**Comment by Suzielen** [comment]
Recebimento dos servomotores OK. Braço robótico encaminhado para  Luis realizar testes com a programação.

**Comment by Suzielen** [comment]
Braço robótico antes da montagem com os servos.
![99c931c86fb7b9db5c7f355440280bbc856ad364](https://user-images.githubusercontent.com/34658037/35699056-4761bc80-0765-11e8-80ae-4fdf9719e39e.jpg)
