### ISSUE TITLE
Visão computacional e Raspberry pi

### ISSUE THREAD

**Issue by TaynaM** [RenatoLAG/Braco-robotico#17]
Pesquisar os programas para a implementação da visão no projeto e verificar e aprender o tipo de linguagem utilizada na plataforma Raspberry pi

**Comment by hyperiondeimos** [comment]
Isso pode ser resumido no issue #22 pois lá vocês colocam todas as dicas de códigos. Apesar de que o código eu vou colocar no dropbox.
