### ISSUE TITLE
Desenhos mecânicos 

### ISSUE THREAD

**Issue by TaynaM** [RenatoLAG/Braco-robotico#19]
Fazer os desenhos mecânicos da esteira e de seus componentes para servirem de material de apoio afim de facilitar a visualização do projeto e para a escrita do artigo.

**Comment by hyperiondeimos** [comment]
Incluindo na Sprint 3

**Comment by vrlimaa** [comment]
Os desenhos mecânicos já estão em finalização e logo mais serão postados logo mais.

**Comment by Luis1404** [comment]
Desenho mecânico em anexo.
[DOC_1.pdf](https://github.com/RenatoLAG/Braco-robotico/files/1692965/DOC_1.pdf)
[DOC_2.pdf](https://github.com/RenatoLAG/Braco-robotico/files/1692966/DOC_2.pdf)
[DOC_3.pdf](https://github.com/RenatoLAG/Braco-robotico/files/1692967/DOC_3.pdf)
