### ISSUE TITLE
Programação do Arduino e da Raspberry 

### ISSUE THREAD

**Issue by TaynaM** [RenatoLAG/Braco-robotico#22]
Inserir aqui as programações do Arduino que irá controlar o braço e a parte de visão computacional que fará o reconhecimento dos objetos. Além disso, disponibilizar o material de apoio que está sendo utilizado.

**Comment by hyperiondeimos** [comment]
Os dados de códigos não são inseridos aqui, ok. Deverão ser inseridos na aba CODE. Podem deixar aqui essa issue, mas deve passar apenas os commits.

**Comment by RenatoLAG** [comment]
**Raspbian Stretch: Install OpenCV 3 + Python on your Raspberry Pi**

https://www.pyimagesearch.com/2017/09/04/raspbian-stretch-install-opencv-3-python-on-your-raspberry-pi/

https://www.youtube.com/watch?v=j6RD3X94rEA&feature=youtu.be

**Comment by RenatoLAG** [comment]
Raspbian Stretch: Install OpenCV 3 + Python on your Raspberry Pi

https://www.youtube.com/watch?v=j6RD3X94rEA&feature=youtu.be

**Comment by RenatoLAG** [comment]
**RASPBERRY PI - INSTALANDO O RASPBIAN | Vídeo Aula #51**

https://www.youtube.com/user/canalwrkits/search?query=RASPBERRY

**Comment by RenatoLAG** [comment]
**Braço Robótico com Arduino**

https://www.youtube.com/watch?v=vVOyWQZ25M8&t=1270s

 **SKETCH - 4 SERVOS:** 

https://www.youtube.com/redirect?q=https%3A%2F%2Fdrive.google.com%2Ffile%2Fd%2F0B91L9po09u35TmU4bHpZNEJjNnc%2Fview%3Fusp%3Dsharing&redir_token=tEHAb0zKFPesvwq9na6FFkYy84x8MTUxNjkwNTYzN0AxNTE2ODE5MjM3&v=vVOyWQZ25M8&event=video_description

**BIBLIOTECA VARSPEEDSERVO:**

https://www.youtube.com/redirect?q=https%3A%2F%2Fdrive.google.com%2Ffile%2Fd%2F0B91L9po09u35SGpyeXNyOWZpQnM%2Fview%3Fusp%3Dsharing&redir_token=tEHAb0zKFPesvwq9na6FFkYy84x8MTUxNjkwNTYzN0AxNTE2ODE5MjM3&v=vVOyWQZ25M8&event=video_description

**Comment by RenatoLAG** [comment]
SKETCH - 4 SERVOS:
