### ISSUE TITLE
Programação do Arduino

### ISSUE THREAD

**Issue by TaynaM** [RenatoLAG/Braco-robotico#27]
Comunicar todo o processo da implementação do Arduino no projeto incluindo as bibliotecas instaladas e a evolução (se houver) da programação.

**Comment by RenatoLAG** [comment]
O Arduino receberá informação vinda da raspberry (via serial) e tratará essa informação, convertendo-a em um movimeto (prédefinido) no braço robótico.

**Comment by Luis1404** [comment]
Para controle dos movimentos dos braços com os servos, foi feito o uso da biblioteca _servo.h_.

**Comment by Luis1404** [comment]
Segue o Código da Programação feita pelo Arduíno:
[Programaçao Braço Robótico.pdf](https://github.com/RenatoLAG/Braco-robotico/files/1692951/Programacao.Braco.Robotico.pdf)

**Comment by hyperiondeimos** [comment]
colocar o código fonte na aba de CODE
