### ISSUE TITLE
Estudo de CLP

### ISSUE THREAD

**Issue by TaynaM** [RenatoLAG/Braco-robotico#28]
Estudar o emprego do clp no projeto.

**Comment by RenatoLAG** [comment]
Aqui está compactado de forma geral um estudo sobre CLP.

[ESTUDO GENERALISTA SOBRE CLP.docx](https://github.com/RenatoLAG/Braco-robotico/files/1693037/ESTUDO.GENERALISTA.SOBRE.CLP.docx)
