### ISSUE TITLE
Tipo de CLP

### ISSUE THREAD

**Issue by TaynaM** [RenatoLAG/Braco-robotico#29]
Definir o tipo ideal do clp que será utilizado no projeto.

**Comment by RenatoLAG** [comment]
O CLP utilizado neste projeto possue saidas a relé.

**Comment by Luis1404** [comment]
Clp utilizado no projeto **Mitsubishi FX 2N
100-240AC 50/60HZ
OUT: 30VDC/240 2A(COS = 1)**
**16 INPUTS, 16 OUTPUTS.**
Segue em anexo materiais de apoio:
[FX2n.pdf](https://github.com/RenatoLAG/Braco-robotico/files/1693098/FX2n.pdf)

**Comment by vrlimaa** [comment]
![Image](https://i.imgur.com/mIsGcAg.jpg)
