### ISSUE TITLE
Programação do CLP

### ISSUE THREAD

**Issue by TaynaM** [RenatoLAG/Braco-robotico#31]
Realizar e disponibilizar a evolução (se houver) da programação do clp.

**Comment by RenatoLAG** [comment]
A programação assim como as instruções utilizadas no clp podem ser facilmente explanada pelo nosso amigo Luís Paulo

**Comment by RenatoLAG** [comment]
A linguagem escolhida para a programação do CLP foi a **Ladder**

**Comment by Luis1404** [comment]
Segue em anexo a programação Ladder, bem como a explicação do programa.

[Programa Ladder.pdf](https://github.com/RenatoLAG/Braco-robotico/files/1692957/Programa.Ladder.pdf)
