### ISSUE TITLE
Definição do projeto

### ISSUE THREAD

**Issue by TaynaM** [RenatoLAG/Braco-robotico#32]
Definir o projeto e suas possíveis aplicações na indústria.

**Comment by Suzielen** [comment]
O projeto consiste em um braço robótico controlado por Arduíno e CLP para controle de um processo. No caso do braço que possui o controle feito pela plataforma Arduíno,  será acionado para pegar a segunda peça que passar pela esteira, a terceira peça será expulsa pelo atuador e a primeira peça passará direto para um marfinite. O controle do atuador e da esteira serão feitos pelo CLP.
