### ISSUE TITLE
Melhorias no projeto

### ISSUE THREAD

**Issue by TaynaM** [RenatoLAG/Braco-robotico#33]
Verificar opções de melhoria para o projeto escolhido.

**Comment by Suzielen** [comment]
Implementar visão computacional para seleção de peças por cor ou matéria prima, seria uma das opções de melhoria para este projeto.

**Comment by TaynaM** [comment]
Além disso, seria bom se tempo de atuação do sistema fosse diminuído para que mais peças pudessem ser colocadas na esteira e, assim, realizar vários ciclos ininterruptos.
