### ISSUE TITLE
Orçamento e custo finais

### ISSUE THREAD

**Issue by TaynaM** [RenatoLAG/Braco-robotico#34]
Disponibilizar todos os gastos com os materiais necessários para o projeto dizendo o local da compra e a quantidade adquirida.

**Comment by Suzielen** [comment]
Segue a planilha atualizada com custos do Projeto.
[Orcamento Final.pdf](https://github.com/RenatoLAG/Braco-robotico/files/1693059/Orcamento.Final.pdf)
[Orcamento Final.xlsx](https://github.com/RenatoLAG/Braco-robotico/files/1693060/Orcamento.Final.xlsx)
