### ISSUE TITLE
Montagem do braço robótico

### ISSUE THREAD

**Issue by TaynaM** [RenatoLAG/Braco-robotico#35]
Realizar a montagem do braço robótico e, em seguida, disponibilizar imagens do mesmo.

**Comment by Suzielen** [comment]
Montagem do braço robótico concluída!

![figura 17](https://user-images.githubusercontent.com/34658037/35738310-de7c57fc-0804-11e8-9da7-f2d1271013c2.PNG)
![figura 18](https://user-images.githubusercontent.com/34658037/35738326-e68c2ecc-0804-11e8-913d-71575806b68e.PNG)

**Comment by Luis1404** [comment]
Feito a programação para controle do Braço Robótico.
