### ISSUE TITLE
Estrutura física do projeto

### ISSUE THREAD

**Issue by TaynaM** [RenatoLAG/Braco-robotico#36]
Definir a estrutura física do projeto com todos os seus detalhes.

**Comment by Suzielen** [comment]
O projeto ira´ dispor de uma esteira com seu funcionamento por um motor DC de 12v, um atuador pneumático , mangueiras pu 6mm, válvulas, sensor óptico pnp, CPL, Arduíno para controle do braço robótico, braço robótico em mdf, servo motores, chaves do tipo push botton para acionamento do sistema e protoboard.

**Comment by Suzielen** [comment]
Disponibilizarei aqui imagens da estrutura física do projeto bem como alguns dos materiais usados: 

![wp_20180204_002](https://user-images.githubusercontent.com/34658037/35778440-9e337040-0994-11e8-99f1-b2b81668ebdf.jpg)
![wp_20180201_002](https://user-images.githubusercontent.com/34658037/35778363-80fb9b7a-0993-11e8-9620-1de6ada3d951.jpg)
![wp_20180202_001](https://user-images.githubusercontent.com/34658037/35778365-812a925e-0993-11e8-9db9-69ba13169206.jpg)
![wp_20180202_003](https://user-images.githubusercontent.com/34658037/35778366-81584c12-0993-11e8-9d20-2556f7b62543.jpg)
![wp_20180202_005](https://user-images.githubusercontent.com/34658037/35778367-818c5912-0993-11e8-86f1-c86d9d0bb1b0.jpg)
![wp_20180202_007](https://user-images.githubusercontent.com/34658037/35778368-81b730ba-0993-11e8-80e5-1dae2a77ec46.jpg)
![wp_20180202_008](https://user-images.githubusercontent.com/34658037/35778369-81e642ba-0993-11e8-8330-87776890c264.jpg)
![wp_20180202_009](https://user-images.githubusercontent.com/34658037/35778370-82156b80-0993-11e8-996d-e8553395312f.jpg)
![wp_20180202_013](https://user-images.githubusercontent.com/34658037/35778371-8247e13c-0993-11e8-985c-3dfa32009402.jpg)
![wp_20180202_004](https://user-images.githubusercontent.com/34658037/35778396-1858c312-0994-11e8-9fd6-2c75c7324630.jpg)
![wp_20180204_002](https://user-images.githubusercontent.com/34658037/35778417-5fc570ba-0994-11e8-9bb5-b18290ba50c3.jpg)
![wp_20180204_003](https://user-images.githubusercontent.com/34658037/35778418-5ff374ce-0994-11e8-8d39-a734ef60e1ef.jpg)
