### ISSUE TITLE
Função do cilindro

### ISSUE THREAD

**Issue by TaynaM** [RenatoLAG/Braco-robotico#42]
Definir a importância do uso do cilindro no projeto.

**Comment by RenatoLAG** [comment]
O atuador pneumático (Cilindro de Dupla ação) para este projeto terá a função de: após a contagem de 3 peças, este atuará retirando a terceira peça da esteira.

**Comment by RenatoLAG** [comment]
Este atuador pneumático se torna indispensável para este projeto, tendo em vista que ele é uma das peças fundamentais do requisito mínimo solicitado pelo professor, para a realizaçao deste projeto.
