### ISSUE TITLE
Vídeo e foto finais

### ISSUE THREAD

**Issue by TaynaM** [RenatoLAG/Braco-robotico#43]
Postar a foto e o vídeo de simulação realizados no dia da entrega do projeto.

**Comment by vrlimaa** [comment]
![imagem 1 braco](https://user-images.githubusercontent.com/35084102/35779484-83ff1efa-09ac-11e8-8431-eff61d8227ae.jpeg)

Braço Robótico utilizado no projeto!

**Comment by vrlimaa** [comment]
![imagem comando pneumatico](https://user-images.githubusercontent.com/35084102/35779495-b4d92a70-09ac-11e8-8c35-0937d314965b.jpeg)

**Comment by vrlimaa** [comment]
![imagem prototipo 1](https://user-images.githubusercontent.com/35084102/35779502-d4fcfd04-09ac-11e8-9b31-a911dd5422d3.jpeg)

![imagem prototipo 3](https://user-images.githubusercontent.com/35084102/35779507-e5354280-09ac-11e8-9c2b-0d18947364fc.jpeg)

![imagem prototipo 2](https://user-images.githubusercontent.com/35084102/35779506-dd66026a-09ac-11e8-997c-bc30502f5d73.jpeg)


Teste de funcionamento do protótipo.

**Comment by vrlimaa** [comment]
![imagem teste1](https://user-images.githubusercontent.com/35084102/35779535-3fcd3d1a-09ad-11e8-82c6-0475b466b704.jpeg)

Teste de funcionamento do braço robótico.

**Comment by vrlimaa** [comment]
[Vídeo do protótipo em funcionamento ](https://www.dropbox.com/s/tle6bzaik0xq80i/V%C3%ADdeo%201.mp4?dl=0)

**Comment by vrlimaa** [comment]
![imagem equipe](https://user-images.githubusercontent.com/35084102/35779812-f7862c7e-09b1-11e8-9450-cf4c34be6aaf.jpeg)

 Equipe (esquerda para direita): @RenatoLAG , @Luis1404, @TaynaM, @Rayara, @vrlimaa, @Suzielen.

**Comment by vrlimaa** [comment]
AQUI ESTÁ TODOS OS COMPONENTES ESSENCIAIS PARA A CONFECÇÃO DO PROJETO!


![whatsapp image 2018-02-04 at 12 50 31](https://user-images.githubusercontent.com/35084102/35779893-b4bffc82-09aa-11e8-9aa0-d09ec11ec1b9.jpeg)
![whatsapp image 2018-02-04 at 12 50 32 1](https://user-images.githubusercontent.com/35084102/35779894-b4e42ba2-09aa-11e8-9bc3-a679677bca1d.jpeg)
![whatsapp image 2018-02-04 at 12 50 32](https://user-images.githubusercontent.com/35084102/35779895-b507db38-09aa-11e8-92f9-68fc62aa961e.jpeg)
![whatsapp image 2018-02-04 at 12 50 33](https://user-images.githubusercontent.com/35084102/35779896-b52a853e-09aa-11e8-99c8-0ce8b2c9e7d9.jpeg)
![whatsapp image 2018-02-04 at 12 50 34 1](https://user-images.githubusercontent.com/35084102/35779897-b54f2e52-09aa-11e8-936b-52cf51794e06.jpeg)
![whatsapp image 2018-02-04 at 12 50 34](https://user-images.githubusercontent.com/35084102/35779898-b5735ca0-09aa-11e8-8eb4-566fbc4abd6a.jpeg)
![whatsapp image 2018-02-04 at 12 50 35 1](https://user-images.githubusercontent.com/35084102/35779899-b59690a8-09aa-11e8-8e16-31fbf54b6095.jpeg)
![whatsapp image 2018-02-04 at 12 50 35](https://user-images.githubusercontent.com/35084102/35779900-b5ba7996-09aa-11e8-8f7d-0e33bfd4102b.jpeg)
![whatsapp image 2018-02-04 at 12 50 36](https://user-images.githubusercontent.com/35084102/35779901-b5ddc6b2-09aa-11e8-8481-111ac9806d78.jpeg)
![whatsapp image 2018-02-04 at 12 54 02](https://user-images.githubusercontent.com/35084102/35779902-b6013232-09aa-11e8-9b06-d00063751c6c.jpeg)

**Comment by hyperiondeimos** [comment]
Bom terem utilizado um CLP, isso deu uma nota a mais para vocês.
