### ISSUE TITLE
Circuitos pneumáticos

### ISSUE THREAD

**Issue by TaynaM** [RenatoLAG/Braco-robotico#44]
Disponibilizar os esquemas pneumáticos do projeto.

**Comment by Luis1404** [comment]
Segue em anexo o circuito eletropneumático:
[Circuito eletropneumático.pdf](https://github.com/RenatoLAG/Braco-robotico/files/1693002/Circuito.eletropneumatico.pdf)

**Comment by hyperiondeimos** [comment]
ok
